spring:
  application:
    name: example-duckdb

vline:
  nodes:
    - name: t1
      duckdb:
        uri: "jdbc:duckdb:"
        data-handler: com.codestepfish.vline.example.duckdb.DuckDataExampleHandler

  struct:
    t1:

